# Options
SHELL=/usr/bin/zsh
set -sg terminal-overrides ",*:RGB"
set -g renumber-windows on
set -g mouse on

set -g pane-border-lines simple
set -g pane-border-style fg=black,bright
set -g pane-active-border-style fg=black,bright

set -g default-terminal 'screen-256color'
set -g default-shell /usr/bin/zsh
set -g prefix2 C-a

set -g base-index 1
set -g pane-base-index 1

# Right
set -g status-right-length 150
set -g status-right-style fg="#e8e6e3"
set -g status-right " #W | #[fg=#ff79c6,bold]#(git -C #{pane_current_path} branch --show-current 2>/dev/null) #[default]| #[fg=#00ff00, bold]#(whoami)@#h #[default]| %H:%M %d %b %Y"

# Left
set -g status-left-length 150
set -g status-left-style fg="#e8e6e3"
set -g status-left "#[fg=#e8e6e3] #S "

# Bindings
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
bind -n C-S-Left  resize-pane -L 5
bind -n C-S-Right resize-pane -R 5
bind -n C-S-Up    resize-pane -U 2
bind -n C-S-Down  resize-pane -D 2

bind e split-window -h -c "#{pane_current_path}" "$SHELL"
bind q split-window -v -c "#{pane_current_path}" "$SHELL"

bind -n C-Tab next-window
bind -n C-S-Tab previous-window

bind r source-file ~/.tmux.conf \; display "Config reloaded!"

setw -g mode-keys vi
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe "xclip -selection clipboard"

# For fixing broken Home and End inputs
bind-key -n Home send Escape "OH"
bind-key -n End send Escape "OF"

set -g status-bg colour234
set -g status-fg colour255

# set -g @host "#H"
# set -g @date "%Y-%m-%d"
# set -g @time "%H:%M"
# set -g status-right "#{@host} | #{@date} | #{@time}"

set-option -g status-right "#H | %H:%M | %Y-%m-%d"
